name: flutter_physics_animation
description: A Flutter package providing physics-based animations with realistic bouncing, gravity, and collision detection.
version: 0.0.1
homepage: https://github.com/Dhia-Bechattaoui/flutter_physics_animation
repository: https://github.com/Dhia-Bechattaoui/flutter_physics_animation
issue_tracker: https://github.com/Dhia-Bechattaoui/flutter_physics_animation/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.0.0

flutter:
  # No assets needed for this package
